{
 "title": "Carbon FEUP",
 "time": { "from": "2024-01-01T01:00:00.000Z", "to": "2024-01-31T23:00:00.000Z" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gCO₂" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SET search_path TO carbono_feup;\r\n\r\nSELECT AVG(grams_per_kw * kw) AS carbon_footprint, energy_usage.datetime\r\nFROM energy_usage\r\nJOIN carbon_data ON carbon_data.datetime=energy_usage.datetime\r\nJOIN locations ON locations.id = energy_usage.location_id \r\nWHERE name = 'Electrotecnia (I)'\r\nAND energy_usage.datetime >= '2024-01-09 00:00:00'\r\nAND energy_usage.datetime < '2024-01-10 00:00:00'\r\nGROUP BY energy_usage.datetime;\r\n"
    },
    {}
   ]
  },
  {
   "title": "DEEC Carbon Footprint 09/01",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SET search_path TO carbono_feup;\r\n\r\nSELECT grams_per_kw * kw AS carbon_footprint, energy_usage.datetime\r\nFROM energy_usage\r\nJOIN carbon_data ON carbon_data.datetime=energy_usage.datetime\r\nJOIN locations ON locations.id = energy_usage.location_id \r\nWHERE name = 'Electrotecnia (I)'\r\nAND energy_usage.datetime >= '2024-01-09 00:00:00'\r\nAND energy_usage.datetime < '2024-01-10 00:00:00'"
    }
   ]
  },
  {
   "title": "DEEC Carbon Footprint 08/01 - 14/01",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SET search_path TO carbono_feup;\r\n\r\nSELECT grams_per_kw * kw AS carbon_footprint, energy_usage.datetime\r\nFROM energy_usage\r\nJOIN carbon_data ON carbon_data.datetime=energy_usage.datetime\r\nJOIN locations ON locations.id = energy_usage.location_id \r\nWHERE name = 'Electrotecnia (I)'\r\nAND energy_usage.datetime >= '2024-01-08'\r\nAND energy_usage.datetime < '2024-01-15'\r\n"
    }
   ]
  },
  {
   "title": "DEEC Carbon Footprint",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "rawSql": "SET search_path TO carbono_feup;\r\n\r\nSELECT grams_per_kw * kw AS carbon_footprint, energy_usage.datetime\r\nFROM energy_usage\r\nJOIN carbon_data ON carbon_data.datetime=energy_usage.datetime\r\nJOIN locations ON locations.id = energy_usage.location_id \r\nWHERE name = 'Electrotecnia (I)'"
    }
   ]
  }
 ]
}