CREATE TABLE IF NOT EXISTS carbon_data (
  datetime TIMESTAMP PRIMARY KEY,
  grams_per_kw REAL
);

CREATE TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT
);

CREATE TABLE IF NOT EXISTS energy_usage (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  datetime TIMESTAMP,
  location_id BIGINT REFERENCES locations(id),
  kw REAL
);

CREATE TABLE IF NOT EXISTS gas_consumption (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  time TIME,
  location_id BIGINT REFERENCES locations(id),
  kw REAL
);
